name: Android Nook Build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # This uses the official GitHub Tool to download the engine
      - name: Fetch Compatible Native Libs
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          mkdir -p app/src/main/jniLibs/armeabi-v7a
          gh release download v2.1.0 --repo koreader/android-luajit-launcher --pattern 'luajit-libs-armeabi-v7a.zip' --output libs.zip
          unzip libs.zip -d temp_libs
          cp -r temp_libs/armeabi-v7a/* app/src/main/jniLibs/armeabi-v7a/
          rm -rf temp_libs libs.zip

      - name: Build Full APK
        run: ./gradlew assembleArmRocksRelease

      - name: Upload Finished APK
        uses: actions/upload-artifact@v4
        with:
          name: KOReader-Nook-Full-Build
          path: app/build/outputs/apk/armRocks/release/*.apk
