name: build
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on: [push, pull_request]
defaults:
  run:
    shell: bash --noprofile --norc -eo pipefail {0}
env:
  BASH_ENV: '/home/ko/.bashrc'
jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        variant: [debug, release]
    name: ${{ matrix.variant }}
    runs-on: ubuntu-latest
    container:
      image: koreader/koandroid:0.9.1-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          clean: false
          fetch-depth: 0
          fetch-tags: true
          show-progress: false

      - name: Build
        run: |
          echo 'android.builder.sdkDownload=false' >>gradle.properties
          ./gradlew app:assembleArmRocks${{ matrix.variant }}

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Nook-GL3-KOReader-${{ matrix.variant }}
          path: app/build/outputs/apk/armRocks/${{ matrix.variant }}/*.apk
